### ISSUE TITLE
Option max-line-length not working

### ISSUE THREAD

**Issue by gandriyko** [SublimeLinter/SublimeLinter-pycodestyle#2] opened 2017-12-23 19:42 UTC
I have set max-line-length to 120, but it still indicate error "line too long (100>89)"
```
"pycodestyle": {
                "@disable": false,
                "args": [],
                "excludes": [],
                "ignore": "",
                "max-line-length": 120,
                "select": ""
            },
```

**Comment by ghost** [comment] 2017-12-23 22:50
Same here, confirmed.

**Comment by ergdev** [comment] 2017-12-30 22:58
The final options are not getting merged into pycodestyle default options in the check method. We can add `pycodestyle_options.__dict__.update(final_options)` just after pycodestyle_options is declared.  It is a bit hacky but I think once the latest version of sublime linter comes out, and the open merge closes this problem will go away. I'm happy to make a quick patch to this in the interim. Thoughts?

**Comment by braver** [comment] 2017-12-31 09:18
I would say drop all the settings and use pycodestyle configuration instead: https://pycodestyle.readthedocs.io/en/latest/intro.html#configuration

Using SublimeLinter settings to configure linters is a really bad idea, other editors or CI cannot use these settings. I’m sorry our plugins have set this example, the sooner we move away from this the better.

**Comment by braver** [comment] 2018-02-08 21:09
Won't fix, using config files *should* work, the settings referenced here are deprecated.

**Closed as completed** 2018-02-08 21:09 UTC

**Comment by nicbou** [comment] 2022-07-27 07:51
Would someone kindly take time to explain the comment above for us who are just getting started?

**Comment by nicbou** [comment] 2022-07-27 07:55
This works for me:

```
// SublimeLinter Settings - User
{
    "linters": {
        "pycodestyle": {
            "max-line-length": 120
        }
    }
}
```
